# Generated by Django 5.1.5 on 2025-01-22 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField()),
                ('return_period', models.IntegerField()),
                ('delivery_date', models.CharField(max_length=50)),
                ('rating_stars', models.FloatField()),
                ('rating_count', models.IntegerField()),
            ],
        ),
    ]
