# Generated by Django 5.1.5 on 2025-04-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='flipkart_products',
        ),
    ]
