services:
  backend:
    build:
      context: ./2-actual-backend
      dockerfile: Dockerfile
    image: sironionrings/node-api:latest
    ports:
      - "8080:8080"
    restart: unless-stopped

  django:
    build:
      context: ./3-django-backend
      dockerfile: Dockerfile
    image: sironionrings/django-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./2-actual-backend:/app/data
    environment:
      - DATA_DIR=/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./3-react-myntra-clone
      dockerfile: Dockerfile
    image: sironionrings/react-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - django
      - backend
    restart: unless-stopped
